const Systemic = require('systemic')
const Express = require('./components/express/express')
const InMemDatabase = require('./components/database/inMemory')
const MongoDb = require('./components/database/mongoDb')
const Model = require('./components/database/model')

module.exports = () => Systemic()
  .add('inMemDatabase', InMemDatabase())
  .add('mongo', MongoDb())
  .add('model', Model())
  .add('express', Express())
  .dependsOn('inMemDatabase', 'model')